# This is manifest for replicaset
apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: my-replicaset
  labels:
    app: my-app
spec:
 template:
   metadata:
     labels:
       app: my-app
   spec:
     containers:
     - name: my-app
       image: nginx
       ports:
        - containerPort: 80
  replicas: 3
  selector:
    matchLabels:
      app: my-app
